/**
 * Google Gemini API Schemas
 *
 * Zod schemas for the Google Gemini GenerateContent API format.
 * Unified schema since Gemini uses the same types for input and output.
 * Only fields and entities used for GenAI translation are explicitly defined.
 * All other fields flow through via .passthrough() to provider metadata.
 */

import { z } from "zod";
import type { Infer } from "$package/utils";

/** Inline blob data (images, audio, etc.) */
export const GoogleBlobSchema = z
  .object({
    data: z.string().optional(),
    mimeType: z.string().optional(),
  })
  .passthrough();
export type GoogleBlob = Infer<typeof GoogleBlobSchema>;

/** File reference by URI */
export const GoogleFileDataSchema = z
  .object({
    fileUri: z.string().optional(),
    mimeType: z.string().optional(),
  })
  .passthrough();
export type GoogleFileData = Infer<typeof GoogleFileDataSchema>;

/** Function call requested by the model */
export const GoogleFunctionCallSchema = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
    args: z.unknown().optional(),
  })
  .passthrough();
export type GoogleFunctionCall = Infer<typeof GoogleFunctionCallSchema>;

/** Function response provided to the model */
export const GoogleFunctionResponseSchema = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
    response: z.unknown().optional(),
  })
  .passthrough();
export type GoogleFunctionResponse = Infer<typeof GoogleFunctionResponseSchema>;

/** Executable code generated by the model */
export const GoogleExecutableCodeSchema = z
  .object({
    code: z.string().optional(),
    language: z.string().optional(),
  })
  .passthrough();
export type GoogleExecutableCode = Infer<typeof GoogleExecutableCodeSchema>;

/** Code execution result */
export const GoogleCodeExecutionResultSchema = z
  .object({
    outcome: z.string().optional(),
    output: z.string().optional(),
  })
  .passthrough();
export type GoogleCodeExecutionResult = Infer<typeof GoogleCodeExecutionResultSchema>;

/** Google-specific part field names that distinguish from GenAI format */
const GOOGLE_PART_FIELDS = [
  "text",
  "inlineData",
  "fileData",
  "functionCall",
  "functionResponse",
  "executableCode",
  "codeExecutionResult",
  "thought",
] as const;

/**
 * Unified Part schema - handles all content types.
 *
 * Gemini uses a single Part type with optional fields for different content types.
 * At most one of these fields should be present: text, inlineData, fileData,
 * functionCall, functionResponse, executableCode, codeExecutionResult.
 *
 * A refinement ensures at least one Google-specific field is present to
 * distinguish from GenAI format (which uses { type: "text", content: "..." }).
 */
export const GooglePartSchema = z
  .object({
    text: z.string().optional(),
    inlineData: GoogleBlobSchema.optional(),
    fileData: GoogleFileDataSchema.optional(),
    functionCall: GoogleFunctionCallSchema.optional(),
    functionResponse: GoogleFunctionResponseSchema.optional(),
    executableCode: GoogleExecutableCodeSchema.optional(),
    codeExecutionResult: GoogleCodeExecutionResultSchema.optional(),
    thought: z.boolean().optional(),
    thoughtSignature: z.string().optional(),
  })
  .passthrough()
  .refine((part) => GOOGLE_PART_FIELDS.some((field) => part[field] !== undefined), {
    message: "Part must have at least one Google-specific field (text, inlineData, fileData, etc.)",
  });
export type GooglePart = Infer<typeof GooglePartSchema>;

/**
 * Content (message) schema.
 *
 * The role is optional and can be 'user' or 'model'.
 * Parts is an array of Part objects.
 */
export const GoogleContentSchema = z
  .object({
    role: z.string().optional(),
    parts: z.array(GooglePartSchema).optional(),
  })
  .passthrough();
export type GoogleContent = Infer<typeof GoogleContentSchema>;

/** System instruction - uses the same Content/Part structure */
export const GoogleSystemSchema = z.union([
  z.string(),
  GoogleContentSchema,
  GooglePartSchema,
  z.array(GooglePartSchema),
]);
export type GoogleSystem = Infer<typeof GoogleSystemSchema>;
